Add a way to configure the number of threads
TeXitoi/par-map pull request #3
Opened 2018-06-11 14:02 UTC by antoine-de

add a `with_nb_threads` that creates a Builder used to configure the number of threads.

I'm not 100% convinced by the implementation since I had to define again all the `ParIter` methods in the `Builder` but it works.

I have not defined the methods `par_{packed}_packed_map` as for we they can be easily created by chaining the `pack` method.

we could also add the `pack` param in the builder bu it would break the api, so it's up to you (and well I don't really need it, so the less work the better :stuck_out_tongue_winking_eye: )

Note: it seems there had been a mistake in crates.io the version in crates.io was 0.1.2
even if the master version was 0.1.1

2018-06-11 17:03 UTC, TeXitoi requested changes
Using the packed variants are not just chaining the two methods, that's more complicated. So please add the forward of the packed method to the builder.

2018-06-11 17:03 UTC, TeXitoi commented on .travis.yml
> +    - rust: nightly
I prefer to use the stable channel for rustfmt now, because that's more... stable ;-)

2018-06-11 17:03 UTC, TeXitoi commented on .travis.yml
> +      env: RUN=TEST
Please remove the allow_failures, I prefer to be notified when nightly fail.

2018-06-11 17:03 UTC, TeXitoi commented on Cargo.toml
> +version = "0.1.3"
That's maybe because I didn't push last publish :/

2018-06-11 17:03 UTC, TeXitoi commented on src/lib.rs
> +    /// ```
You can just forward the documentation to the global par_map doc, something as "As par_map, but with a custom number of threads".

2018-06-11 17:06 UTC, TeXitoi commented
I can't understand your proposition on adding packed to the builder.

2018-06-12 10:18 UTC, TeXitoi commented
I've pushed the 0.1.2

2018-06-12 12:17 UTC, antoine-de commented
forget about my proposal for a builder that also takes a  `nb_pack` as the iter type would be different its complicated.

I don't really understand why the `flat_packed_map` are useful. Can you explain a bit ?

```rust
iter.pack(12)
    .with_nb_threads(4)
    .par_map({...})
```
seems to work well.

2018-06-12 12:25 UTC, TeXitoi commented
In your version, the map function take a `Vec<I::Item>`, not an `I::Item` as in `par_packed_map` and `par_packed_flat_map`

2018-06-12 12:55 UTC, TeXitoi commented
For the `flat_packed_map` that's only ergonomics: you add `packed_` and it works the same.

2018-06-12 15:34 UTC, TeXitoi commented
Stable rustfmt doesn't support the --check flag.

2018-06-12 15:39 UTC, TeXitoi approved these changes

2018-06-12 15:40 UTC, TeXitoi commented on .travis.yml
> +      script: cargo fmt --all -- --check
Can you add a `env: RUN=FMT` here, that's easier to check on Travis if that's the fmt that fail.

2018-06-12 16:47 UTC, merged

2018-06-12 16:50 UTC, TeXitoi commented
v0.1.3 published.

2018-06-12 18:43 UTC, antoine-de commented
thanks!